import { Language } from "./types";

export const ETH_USD = 1000;
export const WBTC_USD = 10000;
export const USDC = 1;

export const supportedNetworks = [
  { name: "Ethereum", chainId: 1, src: "/logos/png/eth-logo.png" },
  {
    name: "Unichain",
    chainId: 130,
    src: "/logos/png/unichain-logo.png",
    isNew: true,
  },
  { name: "Polygon", chainId: 137, src: "/logos/png/polygon-logo.png" },
  { name: "OP Mainnet", chainId: 10, src: "/logos/png/optimism-logo.png" },
  { name: "Arbitrum", chainId: 42161, src: "/logos/png/arbitrum-logo.png" },
  { name: "Base", chainId: 8453, src: "/logos/png/base-logo.png" },
  { name: "BNB Chain", chainId: 56, src: "/logos/png/bnb-logo.png" },
  { name: "Blast", chainId: 100, src: "/logos/png/blast-logo.png" },
  { name: "Avalanche", chainId: 43114, src: "/logos/png/avalanche-logo.png" },
  { name: "Celo", chainId: 42220, src: "/logos/png/celo-logo.png" },
  { name: "World Chain", chainId: 480, src: "/logos/png/world-chain-logo.png" },
  { name: "Zora Network", chainId: 7777777, src: "/logos/png/zora-logo.png" },
  { name: "ZkSync", chainId: 324, src: "/logos/png/zksync-logo.png" },
];
export const LANGUAGES_CODE = [
  "afrikaans",
  "arabic",
  "catalan",
  "chineseSimplified",
  "chineseTraditional",
  "czech",
  "danish",
  "dutch",
  "english",
  "finnish",
  "french",
  "greek",
  "hebrew",
  "hindi",
  "hungarian",
  "indonesian",
  "italian",
  "japanese",
  "korean",
  "malay",
  "norwegian",
  "polish",
  "portuguese",
  "romanian",
  "russian",
  "serbian",
  "spanishLatam",
  "spanishSpain",
  "spanishUs",
  "swahili",
  "swedish",
  "turkish",
  "ukrainian",
  "urdu",
  "vietnamese",
];
export const WEB_SUPPORTED_LANGUAGES = [
  Language.English,
  Language.Afrikaans,
  Language.Arabic,
  Language.Catalan,
  Language.ChineseSimplified,
  Language.ChineseTraditional,
  Language.Danish,
  Language.Dutch,
  Language.Finnish,
  Language.French,
  Language.Greek,
  Language.Hebrew,
  Language.Hindi,
  Language.Hungarian,
  Language.Indonesian,
  Language.Italian,
  Language.Japanese,
  Language.Korean,
  Language.Malay,
  Language.Polish,
  Language.Portuguese,
  Language.Russian,
  Language.Serbian,
  Language.SpanishSpain,
  Language.SpanishLatam,
  Language.SpanishUnitedStates,
  Language.Swahili,
  Language.Swedish,
  Language.Turkish,
  Language.Ukrainian,
  Language.Urdu,
  Language.Vietnamese,
];
export const countryName: Record<string, string> = {
  "af-ZA": "afrikaans",
  "ar-SA": "arabic",
  "ca-ES": "catalan",
  zh: "chineseSimplified",
  "zh-Hant": "chineseTraditional",
  "cs-CZ": "czech",
  "da-DK": "danish",
  "nl-NL": "dutch",
  "en-US": "english",
  "fi-FI": "finnish",
  "fr-FR": "french",
  "el-GR": "greek",
  "he-IL": "hebrew",
  "hi-IN": "hindi",
  "hu-HU": "hungarian",
  "id-ID": "indonesian",
  "it-IT": "italian",
  "ja-JP": "japanese",
  "ko-KR": "korean",
  "ms-MY": "malay",
  "no-NO": "norwegian",
  "pl-PL": "polish",
  "pt-PT": "portuguese",
  "ro-RO": "romanian",
  "ru-RU": "russian",
  "sr-SP": "serbian",
  "es-419": "spanishLatam",
  "es-ES": "spanishSpain",
  "es-US": "spanishUs",
  "sw-TZ": "swahili",
  "sv-SE": "swedish",
  "tr-TR": "turkish",
  "uk-UA": "ukrainian",
  "ur-PK": "urdu",
  "vi-VN": "vietnamese",
};

export enum FiatCurrency {
  AustralianDollar = "AUD",
  BrazilianReal = "BRL",
  CanadianDollar = "CAD",
  ChineseYuan = "CNY",
  Euro = "EUR",
  BritishPound = "GBP",
  HongKongDollar = "HKD",
  IndonesianRupiah = "IDR",
  IndianRupee = "INR",
  JapaneseYen = "JPY",
  NigerianNaira = "NGN",
  PakistaniRupee = "PKR",
  RussianRuble = "RUB",
  SingaporeDollar = "SGD",
  SouthKoreanWon = "KRW",
  ThaiBaht = "THB",
  TurkishLira = "TRY",
  UkrainianHryvnia = "UAH",
  UnitedStatesDollar = "USD",
  VietnameseDong = "VND",
}

export const DEFAULT_LOCAL_CURRENCY: FiatCurrency =
  FiatCurrency.UnitedStatesDollar;

export const ORDERED_CURRENCIES: FiatCurrency[] = [
  FiatCurrency.UnitedStatesDollar,
  FiatCurrency.AustralianDollar,
  FiatCurrency.BrazilianReal,
  FiatCurrency.CanadianDollar,
  FiatCurrency.ChineseYuan,
  FiatCurrency.Euro,
  FiatCurrency.BritishPound,
  FiatCurrency.HongKongDollar,
  FiatCurrency.IndonesianRupiah,
  FiatCurrency.IndianRupee,
  FiatCurrency.JapaneseYen,
  FiatCurrency.SouthKoreanWon,
  FiatCurrency.NigerianNaira,
  FiatCurrency.PakistaniRupee,
  FiatCurrency.RussianRuble,
  FiatCurrency.SingaporeDollar,
  FiatCurrency.ThaiBaht,
  FiatCurrency.TurkishLira,
  FiatCurrency.UkrainianHryvnia,
  FiatCurrency.VietnameseDong,
];
